FROM node:20 AS build

ARG PORT=3010
ENV PORT=${PORT}

WORKDIR /src
COPY package*.json ./
COPY webpack.config.js ./
COPY .babelrc ./
#RUN npm ci
RUN yarn
COPY ./src ./src
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=build /src/dist /usr/share/nginx/html
EXPOSE $PORT
