FROM python:3.12-slim

RUN pip install --upgrade pip
RUN pip install gunicorn

RUN pip install celery

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./app.py

ENV FLASK_APP=app.py

CMD ["gunicorn", "--bind", "0.0.0.0:5001", "app:app"]
EXPOSE 5001
