FROM mariadb:10.6

ARG PORT=3306

COPY my.cnf /etc/mysql/conf.d/my.cnf

RUN chmod 644 /etc/mysql/conf.d/my.cnf

COPY migrations/oscarinit.sql /oscarinit.sql
COPY migrations/oscardata.sql /oscardata.sql

COPY migrations/initcaisi.sql /initcaisi.sql
COPY migrations/initcaisi_data.sql /initcaisi_data.sql

COPY migrations/patch19.sql /patch19.sql

COPY migrations/oscarinit_bc.sql /oscarinit_bc.sql
COPY migrations/oscardata_bc.sql /oscardata_bc.sql

EXPOSE $PORT
